// Menu design templates the owner can choose for their public menu.
// Every class string must be a literal so Tailwind picks it up at build time.

export const MENU_THEMES = {
  classic: {
    name: 'Classic',
    tagline: 'Clean & friendly — works for every restaurant',
    emoji: '🍽️',
    page: 'bg-gray-50 text-gray-900',
    header: 'bg-gradient-to-br from-brand-500 via-brand-600 to-brand-700 text-white',
    headerSub: 'text-white/80',
    nav: 'border-gray-200/70 bg-white/85',
    pill: 'border-gray-200 bg-white text-gray-700 hover:border-brand-300 hover:bg-brand-50 hover:text-brand-700',
    heading: 'text-gray-900',
    card: 'bg-white border border-gray-200/80 shadow-card',
    cardActive: 'ring-2 ring-brand-500/30 border-brand-200',
    desc: 'text-gray-500',
    price: 'text-gray-900',
    addBtn: 'btn bg-gradient-to-br from-brand-500 to-brand-700 text-white shadow-glow-sm hover:brightness-110',
    qtyMinus: 'btn border border-gray-300 bg-white text-gray-700',
    qtyText: 'text-gray-900',
    cartBar: 'btn bg-gradient-to-br from-brand-500 to-brand-700 text-white shadow-glow',
    sheet: 'bg-white text-gray-900',
    sheetMuted: 'text-gray-500',
    sheetBorder: 'border-gray-200',
    input: 'input',
  },
  midnight: {
    name: 'Midnight',
    tagline: 'Dark & elegant — bars, lounges, fine dining',
    emoji: '🥂',
    page: 'bg-ink-950 text-ink-200',
    header: 'bg-gradient-to-br from-ink-900 via-ink-850 to-ink-800 text-white border-b border-amber-400/20',
    headerSub: 'text-ink-300',
    nav: 'border-white/10 bg-ink-950/85',
    pill: 'border-white/15 bg-white/5 text-ink-200 hover:border-amber-400/50 hover:bg-amber-400/10 hover:text-amber-300',
    heading: 'text-white',
    card: 'bg-white/5 border border-white/10',
    cardActive: 'ring-2 ring-amber-400/40 border-amber-400/40',
    desc: 'text-ink-400',
    price: 'text-amber-400',
    addBtn: 'btn bg-amber-500 font-bold text-ink-950 hover:bg-amber-400',
    qtyMinus: 'btn border border-white/20 bg-white/5 text-white',
    qtyText: 'text-white',
    cartBar: 'btn bg-amber-500 font-bold text-ink-950 shadow-[0_0_40px_-8px_rgba(245,158,11,0.5)]',
    sheet: 'bg-ink-900 text-white',
    sheetMuted: 'text-ink-400',
    sheetBorder: 'border-white/10',
    input: 'input-dark',
  },
  warm: {
    name: 'Warm Cafe',
    tagline: 'Cozy terracotta — cafes, bakeries, brunch spots',
    emoji: '☕',
    page: 'bg-[#faf3ea] text-stone-800',
    header: 'bg-gradient-to-br from-orange-700 via-orange-600 to-amber-600 text-white',
    headerSub: 'text-orange-100',
    nav: 'border-orange-200/60 bg-[#faf3ea]/90',
    pill: 'border-orange-200 bg-white text-stone-700 hover:border-orange-400 hover:bg-orange-100 hover:text-orange-800',
    heading: 'text-stone-900',
    card: 'bg-white border border-orange-100 shadow-card',
    cardActive: 'ring-2 ring-orange-400/40 border-orange-300',
    desc: 'text-stone-500',
    price: 'text-orange-700',
    addBtn: 'btn bg-orange-600 text-white hover:bg-orange-700',
    qtyMinus: 'btn border border-orange-200 bg-white text-stone-700',
    qtyText: 'text-stone-900',
    cartBar: 'btn bg-orange-600 text-white shadow-[0_0_40px_-8px_rgba(234,88,12,0.5)]',
    sheet: 'bg-white text-stone-800',
    sheetMuted: 'text-stone-500',
    sheetBorder: 'border-orange-100',
    input: 'input',
  },
  fresh: {
    name: 'Fresh',
    tagline: 'Crisp greens — healthy food, juice bars, veg kitchens',
    emoji: '🥗',
    page: 'bg-emerald-50/60 text-gray-900',
    header: 'bg-gradient-to-br from-emerald-600 via-emerald-700 to-teal-700 text-white',
    headerSub: 'text-emerald-100',
    nav: 'border-emerald-200/60 bg-white/85',
    pill: 'border-emerald-200 bg-white text-gray-700 hover:border-emerald-400 hover:bg-emerald-50 hover:text-emerald-800',
    heading: 'text-gray-900',
    card: 'bg-white border border-emerald-100 shadow-card',
    cardActive: 'ring-2 ring-emerald-500/30 border-emerald-300',
    desc: 'text-gray-500',
    price: 'text-emerald-700',
    addBtn: 'btn bg-emerald-600 text-white hover:bg-emerald-700',
    qtyMinus: 'btn border border-emerald-200 bg-white text-gray-700',
    qtyText: 'text-gray-900',
    cartBar: 'btn bg-emerald-600 text-white shadow-[0_0_40px_-8px_rgba(5,150,105,0.5)]',
    sheet: 'bg-white text-gray-900',
    sheetMuted: 'text-gray-500',
    sheetBorder: 'border-emerald-100',
    input: 'input',
  },
};

export function getMenuTheme(key) {
  return MENU_THEMES[key] || MENU_THEMES.classic;
}
