// Professional menu TEMPLATES for the public menu.
// Each template has a distinct LAYOUT (structure), not just colors —
// inspired by fine-dining / 5-star hotel menus.
// Class strings must be literal so Tailwind picks them up at build time.

export const MENU_THEMES = {
  // 1. ÉLÉGANCE — fine-dining editorial. Serif type, gold accents, dotted
  //    price leaders, small round thumbnails. The classic luxury hotel look.
  elegance: {
    name: 'Élégance',
    tagline: 'Fine dining — serif type, gold accents, dotted price leaders',
    emoji: '✦',
    layout: 'elegant',
    page: 'bg-[#f7f2e9] text-stone-800',
    hero: 'bg-[#14110d] text-[#ece0c6]',
    heroName: 'font-serif',
    heroSub: 'text-[#c2a878]',
    heroRule: 'bg-[#b08d4c]',
    nav: 'border-[#e3d8c1] bg-[#f7f2e9]/90',
    pill: 'border-[#d9c9a6] bg-white/70 text-stone-600 hover:border-[#b08d4c] hover:text-[#8a6d2f]',
    catTitle: 'font-serif text-[#14110d]',
    catRule: 'bg-[#cbb587]',
    name: 'font-serif text-stone-900',
    desc: 'text-stone-500 italic',
    price: 'font-serif text-[#8a6d2f]',
    leader: 'border-[#cdb98f]',
    addBtn: 'bg-[#14110d] text-[#ece0c6] hover:bg-black',
    qtyMinus: 'border border-[#d9c9a6] bg-white text-stone-700',
    qtyText: 'text-stone-900',
    cartBar: 'bg-[#14110d] text-[#ece0c6] shadow-[0_0_40px_-8px_rgba(176,141,76,0.55)]',
    sheet: 'bg-[#f7f2e9] text-stone-800',
    sheetName: 'font-serif',
    sheetMuted: 'text-stone-500',
    sheetBorder: 'border-[#e3d8c1]',
    input: 'input',
  },

  // 2. GALLERY — photo-forward. Each dish is a big card with a large image
  //    and a bottom detail bar. Modern hotel all-day-dining app feel.
  gallery: {
    name: 'Gallery',
    tagline: 'Photo-forward — big food images, bold cards',
    emoji: '📸',
    layout: 'gallery',
    page: 'bg-neutral-100 text-neutral-900',
    hero: 'bg-neutral-900 text-white',
    heroName: 'font-display',
    heroSub: 'text-neutral-300',
    heroRule: 'bg-brand-500',
    nav: 'border-neutral-200 bg-neutral-100/90',
    pill: 'border-neutral-300 bg-white text-neutral-700 hover:border-neutral-900 hover:bg-neutral-900 hover:text-white',
    catTitle: 'font-display text-neutral-900',
    catRule: 'bg-neutral-300',
    name: 'font-display text-neutral-900',
    desc: 'text-neutral-500',
    price: 'font-display text-neutral-900',
    addBtn: 'bg-neutral-900 text-white hover:bg-black',
    qtyMinus: 'border border-neutral-300 bg-white text-neutral-800',
    qtyText: 'text-neutral-900',
    cartBar: 'bg-neutral-900 text-white shadow-[0_0_40px_-8px_rgba(0,0,0,0.5)]',
    imgPlaceholder: 'bg-gradient-to-br from-neutral-200 to-neutral-300 text-neutral-400',
    sheet: 'bg-white text-neutral-900',
    sheetName: 'font-display',
    sheetMuted: 'text-neutral-500',
    sheetBorder: 'border-neutral-200',
    input: 'input',
  },

  // 3. NOIR — dark luxury photo layout. Full-bleed dark cards, emerald/gold
  //    accents. Cocktail bars, rooftop lounges, chef's table.
  noir: {
    name: 'Noir',
    tagline: 'Dark luxury — moody photos, emerald accents',
    emoji: '🌙',
    layout: 'gallery',
    page: 'bg-[#0d0d0f] text-neutral-200',
    hero: 'bg-gradient-to-b from-[#17171b] to-[#0d0d0f] text-white border-b border-emerald-400/20',
    heroName: 'font-serif',
    heroSub: 'text-emerald-300/80',
    heroRule: 'bg-emerald-400',
    nav: 'border-white/10 bg-[#0d0d0f]/90',
    pill: 'border-white/15 bg-white/5 text-neutral-300 hover:border-emerald-400/60 hover:text-emerald-300',
    catTitle: 'font-serif text-white',
    catRule: 'bg-white/15',
    name: 'font-serif text-white',
    desc: 'text-neutral-400',
    price: 'font-serif text-emerald-300',
    addBtn: 'bg-emerald-500 font-semibold text-[#0d0d0f] hover:bg-emerald-400',
    qtyMinus: 'border border-white/20 bg-white/5 text-white',
    qtyText: 'text-white',
    cartBar: 'bg-emerald-500 font-semibold text-[#0d0d0f] shadow-[0_0_40px_-8px_rgba(16,185,129,0.6)]',
    imgPlaceholder: 'bg-gradient-to-br from-neutral-800 to-neutral-900 text-neutral-600',
    sheet: 'bg-[#17171b] text-white',
    sheetName: 'font-serif',
    sheetMuted: 'text-neutral-400',
    sheetBorder: 'border-white/10',
    input: 'input-dark',
  },

  // 4. GRID — clean 2-up photo tiles. Cafes, bakeries, casual-but-polished.
  grid: {
    name: 'Grid',
    tagline: 'Photo tiles — compact 2-up grid, warm & clean',
    emoji: '▦',
    layout: 'grid',
    page: 'bg-[#fbf7f2] text-stone-800',
    hero: 'bg-gradient-to-br from-orange-600 to-amber-600 text-white',
    heroName: 'font-display',
    heroSub: 'text-orange-100',
    heroRule: 'bg-white/50',
    nav: 'border-orange-200/60 bg-[#fbf7f2]/90',
    pill: 'border-orange-200 bg-white text-stone-700 hover:border-orange-400 hover:bg-orange-50 hover:text-orange-800',
    catTitle: 'font-display text-stone-900',
    catRule: 'bg-orange-200',
    name: 'text-stone-900',
    desc: 'text-stone-500',
    price: 'font-display text-orange-700',
    addBtn: 'bg-orange-600 text-white hover:bg-orange-700',
    qtyMinus: 'border border-orange-200 bg-white text-stone-700',
    qtyText: 'text-stone-900',
    cartBar: 'bg-orange-600 text-white shadow-[0_0_40px_-8px_rgba(234,88,12,0.5)]',
    imgPlaceholder: 'bg-gradient-to-br from-orange-100 to-amber-100 text-orange-300',
    sheet: 'bg-white text-stone-800',
    sheetName: 'font-display',
    sheetMuted: 'text-stone-500',
    sheetBorder: 'border-orange-100',
    input: 'input',
  },
};

export function getMenuTheme(key) {
  return MENU_THEMES[key] || MENU_THEMES.elegance;
}
